---
name: CI
on: [push, pull_request]

jobs:
  checkgomod:
    name: check go.mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - run: go mod tidy -v
      - name: Check for changes in go.mod
        run: |
          git diff --name-only --exit-code go.mod || ( git diff && echo "Run go tidy to update go.mod" && false )
